name: Backend Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Backend Tests
    timeout-minutes: 10
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: password 
          MYSQL_DATABASE: mydb 
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3 # サービスのヘルスチェックを設定する
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
        working-directory: ./back
      - name: Setup Prisma
        run: npx prisma generate
        working-directory: ./back
      - name: Import SQL file
        run: |
          mysql -h 127.0.0.1 --port 3306 -u root -ppassword mydb < ./docker/sql/01_create_database.sql
          mysql -h 127.0.0.1 --port 3306 -u root -ppassword mydb < ./docker/sql/02_create_table.sql
          mysql -h 127.0.0.1 --port 3306 -u root -ppassword mydb < ./docker/sql/03_insert_table.sql
      - name: Run tests
        run: npm run test
        working-directory: ./back
        env:
          DATABASE_URL: "mysql://root:password@localhost:3306/mydb"
