name: Backend Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    working-directory: ./back

jobs:
  test:
    name: Backend Tests
    timeout-minutes: 10
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: password 
          MYSQL_DATABASE: mydb 
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3 # サービスのヘルスチェックを設定する
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Setup Prisma
        run: npx prisma generate
      - name: Import sql to db
        run: |
          mysql -h 127.0.0.1 -P 3306 -u root --password=password -e "$(cat $(find ../docker/sql -name '*.sql' | sort))"
      - name: Run tests
        run: npm run test
        env:
          DATABASE_URL: "mysql://root:password@localhost:3306/mydb"
