name: Frontend Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    working-directory: ./front

jobs:
  test:
    name: Frontend Tests on ${{ matrix.os }}
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # 特定の job が失敗しても他の job をキャンセルしない
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    services:
      mysql:
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: password 
          MYSQL_DATABASE: mydb 
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3 # サービスのヘルスチェックを設定する
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Install browsers
        run: npx playwright install --with-deps
      - name: Start front
        run: |
          npm run build
          npm run start &
      - name: Run tests
        run: npx playwright test
