name: Frontend Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test on ${{ matrix.os }} and ${{ matrix.browser }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        browser: [chromium, firefox, webkit]
        include:
          - os: windows-latest
            browser: webkit
            skip: true # Playwright does not support WebKit on Windows yet
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
        working-directory: ./front
      - name: Install browsers
        run: npx playwright install --with-deps
        working-directory: ./front
      - name: Run tests
        if: ${{ !matrix.skip }}
        run: npx playwright test --browser=${{ matrix.browser }}
        working-directory: ./front
